Fix for pacemaker proposal migration failure
This fix resolves the issue where the migration of pacemaker
proposals fail with the following error:

rake aborted!
Failed to migrate proposal data for pacemaker: error while executing
migration script /opt/dell/chef/data_bags/crowbar/migrate/pacemaker/
102_add_ring_array.rb:
undefined method `[]' for #<Chef::Role:0x00000008b3d618>
/opt/dell/crowbar_framework/lib/schema_migration.rb:224:in `rescue
in migrate_proposal'

(cherry picked from commit 6e5eaaf)